server:
  port: 8090
spring:
  data:
    mongodb:
      username: linho
      password: linho
      host: localhost
      port: 27017
      database: classe
      authentication-database: admin