server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: class-service
          uri: lb:http://CLASS-SERVICE
          predicates:
            - Path=/api/v1/class/**
        - id: salle-service
          uri: lb:http://CLASS-SERVICE
          predicates:
            - Path=/api/v1/salles/**
        - id: etudiant-service
          uri: lb:http://ETUDIANT-SERVICE
          predicates:
            - Path=/api/v1/etudiants/**
        - id: inscription-service
          uri: lb:http://ETUDIANT-SERVICE
          predicates:
            - Path=/api/v1/inscriptions/**
        - id: notification-service
          uri: lb:http://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**
        - id: cours-service
          uri: lb:http://COURS-SERVICE
          predicates:
            - Path=/api/v1/cours/**
        - id: matiere-service
          uri: lb:http://COURS-SERVICE
          predicates:
            - Path=/api/v1/matiere/**
        - id: professeur-service
          uri: lb:http://PROFESSEUR-SERVICE
          predicates:
            - Path=/api/v1/professeurs/**
        - id: emploi-service
          uri: lb:http://EMPLOI-SERVICE
          predicates:
            - Path=/api/v1/creneau/**
        - id: description-service
          uri: lb:http://EMPLOI-SERVICE
          predicates:
            - Path=/api/v1/description/**


