services:

  terraform:
    image: hashicorp/terraform:1.5.0
    volumes:
      - ./infrastructure/terraform:/terraform
      - terraform_plugins:/root/.terraform.d/plugins
      - terraform_cache:/root/.terraform.d/plugin-cache
      - ~/.aws:/root/.aws
    environment:
#      - AWS_ACCESS_KEY_ID=minioadmin
#      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_DEFAULT_REGION=eu-west-3
      - TF_PLUGIN_CACHE_DIR=/root/.terraform.d/plugin-cache
    working_dir: /terraform
    entrypoint: [ "terraform" ]

  minio:
    image: minio/minio
    ports:
      - "9900:9000"
      - "9901:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"


  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5000:5000"
    volumes:
      -  registry_data:/var/lib/registry
    restart: always

  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=linho
      - MONGO_INITDB_ROOT_PASSWORD=linho

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8181:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=linho
      - ME_CONFIG_MONGODB_ADMINPASSWORD=linho
      - ME_CONFIG_MONGODB_SERVER=mongodb

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - microservices-net

  keycloak:
    container_name: keycloak-ms
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9098:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - microservices-net
    command:
      - "start-dev"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ms_kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    networks:
      - microservices-net

  mail-dev:
    container_name: ms-mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  microservices-net:
    driver: bridge

volumes:
  mongo:
  registry_data:
  minio_data:
  terraform_plugins:
  terraform_cache: