apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: dev
spec:
  selector:
    app: discovery-service
  ports:
    - port: 8761
      targetPort: 8761
  type: ClusterIP