apiVersion: v1
kind: ConfigMap
metadata:
  name: cours-service-config
  namespace: dev
data:
  application.properties: |
    spring.application.name=cours-service
    server.port=8013
    management.endpoints.web.exposure.include=*
    management.endpoint.health.show-details=always
    management.metrics.tags.application=${spring.application.name}
    spring.data.mongodb.host=mongodb
    spring.data.mongodb.port=27017
    spring.data.mongodb.database=cours
    spring.data.mongodb.username=linho
    spring.data.mongodb.password=linho
    spring.data.mongodb.authentication-database=admin
    application.config.professeur-url=http://gateway-service/api/v1/professeurs
    application.config.classe-url=http://gateway-service/api/v1/class