apiVersion: v1
kind: ConfigMap
metadata:
  name: classe-service-config
  namespace: dev
data:
  application.properties: |
    spring.application.name=classe-service
    server.port=8090
    management.endpoints.web.exposure.include=*
    management.endpoint.health.show-details=always
    management.metrics.tags.application=${spring.application.name}
    spring.data.mongodb.host=mongodb
    spring.data.mongodb.port=27017
    spring.data.mongodb.database=classe
    spring.data.mongodb.username=linho
    spring.data.mongodb.password=linho
    spring.data.mongodb.authentication-database=admin