apiVersion: v1
kind: Service
metadata:
  name: professeur-service
  namespace: dev
spec:
  selector:
    app: professeur-service
  ports:
    - port: 80
      targetPort: 8015
  type: ClusterIP