apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-service-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gestion-etablissement-isi/gestion-etablissement-backend-microservice.git
    targetRevision: main
    path: k8s/dev/gateway-service
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true